config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :charges, only: [:new , :create]
  resources :events
  


  resources :events do
  post "/subscribe" , to: "events#subscribe" 
end

resources :devise
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "user/:id" , to: "events#userpage" , as: "profil"
  
end
  
  

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator , class_name: "User"
	has_and_belongs_to_many :attendees , class_name: "User"
	validates :description, presence: true , length: {minimum: 6}
	validates :date, presence: true
	validates :place, presence: true
	scope :current , -> {where("date > ?" , DateTime.now)}
	scope :past , -> {where("date < ?" , DateTime.now)}
end
 

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end
  def userpage
    @events = Event.where(:creator_id => current_user.id).all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create

    @event = Event.new(event_params)
      @event.creator_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "L'evenement a bien été crée !" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
    end

    def subscribe
     @event = Event.find(params[:event_id])
       if @event.attendees.include? current_user
        flash[:error] = "Tu as déja payé !"
        redirect_to @event
        return
  end


     # Amount in cents
  @amount = @event.price

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'eur'
  )

    @event.attendees << current_user
    flash[:success] = "Tu participes bien à l'évènement "
    redirect_to @event


rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to @event
end

    
 





  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "L'evenement a bien été mis à jour !" }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "L'evenement a bien été supprimé !" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :description, :place, :price, :creator_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Lieu %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :prix %>
    <%= form.number_field :price %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Évènements</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Lieu</th>
      <th>Prix</th>
      <th></th>
      <th></th>
      <th>Createur de l'évènement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.current.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= event.place %></td>
        <td><%= event.price %></td>
        <td></td>
        <td></td>
        <td><%= User.find(event.creator_id).email %></td>
        <td><%= link_to 'Voir', event %></td>
        <% if current_user == event.creator  %>
        <td><%= link_to 'Editer', edit_event_path(event) %></td>
        <td><%= link_to 'Supprimer', event, method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %></td>
        <% elsif event.attendees.include? current_user %>
        <td> Tu participes à cet évènement</td>
       <% else %>

       <td><%= link_to  "S'inscrire" , event_path(event.id) %></td>
       
       
      </tr>
      <% end %>

    <% end %>
  </tbody>
</table>
<br>
<hr>
<br>

<h2>Évènements passés</h2>
<br>

<br>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Lieu</th>
      <th>Prix</th>
      <th></th>
      <th></th>
      <th>Createur de l'évènement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.past.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= event.place %></td>
        <td><%= event.price %></td>
        <td></td>
        <td></td>
        <td><%= User.find(event.creator_id).email %></td>
        <td><%= link_to 'Voir', event %></td>

        </tr>
      <% end %>

    
  </tbody>
</table>

<br>
<%= link_to 'Nouvel évènement', new_event_path %>

app/views/events/new.html.erb
<h1>Nouveaux évènement</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @event.price%> Euros
</p>

<p>
  <strong>Createur de l'évènement:</strong>
  <%= User.find(@event.creator_id).email %>

</p>

<div class="text-center-right">
<%= form_tag event_subscribe_path(@event) do %>
  <article>
    <% if flash[:error].present? %>
      
    <% end %>
    <label class="amount">
      <p>Pour rejoindre l'évènement, Merci de payer le prix du ticket : <%= @event.price.to_f   %> €</p>
      
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Prix de l'evenement"
          data-amount="<%= (@event.price)*100 %>"
          data-currency="eur"
          data-locale="auto"></script>

<% end %>
</div>
<h2>Liste des participants</h2>
<table>

  <% @event.attendees.each do |attendee|%>
  <tr>
    <td><%= attendee.email %></td>
  </tr>
<% end %>
</table>

app/views/events/userpage.html.erb
<p id="notice"><%= notice %></p>

<h1> Mes évènements </h1>

<table>
  <thead>
    <tr>
      <td>Date</td>
      <td>Description</td>
      <td>Lieu</td>
      <td>Prix</td>
      <td>Créateur de l'évènement</td>
      <td colspan="3"></td>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= event.place %></td>
        <td><%= event.price %></td>
        <td><%= event.creator_id %></td>
        <td><%= link_to 'Voir', event %></td>
        
        <td><%= link_to 'Editer', edit_event_path(event) %></td>
        <td><%= link_to 'Supprimer', event, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>
     
      </tr>
      

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvel évènement', new_event_path %>