config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :charges, only: [:new , :create]
  resources :events
  


  resources :events do
  post "/subscribe" , to: "events#subscribe" 
end

resources :devise
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "user/:id" , to: "events#userpage" , as: "profil"
  
end
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="bootstrap/js/jquery.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">EventBriteLike</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Accueil</a></li>
      <% if user_signed_in? %> 
       <li> <%= link_to "Mes évènements", profil_path(:id) %> </li>
        <li> <%= link_to "Tout les évènements", events_path %> </li>
        <li><%= link_to "Se deconnecter", destroy_user_session_path , method: :delete %> </li>
        <% else %>
      <li> <%= link_to "Se connecter", new_user_session_path %> </li>
      <li><%= link_to "S'enregistrer", new_user_registration_path %> </li>
       <% end %>
      
    </ul>
  </div>
</nav>
  </head>

  <body>
    <div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>
    
  </body>
</html>